import "./globals.css";
import "./force.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundImage: `url("https://framerusercontent.com/images/5oNpsohqItnG7gj1CItFRE5tzE.jpg")`,
          backgroundSize: "55%",
          backgroundPosition: "right 0px top 0px",
          backgroundRepeat: "no-repeat",
          backgroundColor: "#000",
        }}
      >
        {children}
      </body>
    </html>
  );
}
